Chapter 3 Examples
================

-----

### Example 3-2-1

To obtain the sample covariance for the height and weight data in Table
3.1, we first calculate \(x\), \(y\), and \(\sum_{i}x_{i}y{i}\), where
\(x\) is height and \(y\) is weight:

``` r
#defining vectors x and y
x=c(69,74,68,70,72,67,66,70,76,68,72,79,74,67,66,71,74,75,75,76)
y=c(153,175,155,135,172,150,115,137,200,130,140,265,
    185,112,140,150,165,185,210,220)
xbar=mean(x)
ybar=mean(y)

#printing
x
```

    ##  [1] 69 74 68 70 72 67 66 70 76 68 72 79 74 67 66 71 74 75 75 76

``` r
y
```

    ##  [1] 153 175 155 135 172 150 115 137 200 130 140 265 185 112 140 150 165 185 210
    ## [20] 220

``` r
xbar
```

    ## [1] 71.45

``` r
ybar
```

    ## [1] 164.7

``` r
#defining covariance between x and y
Sxy=cov(x,y)
Sxy
```

    ## [1] 128.8789

``` r
#rounding covariance to two decimals
RoSxy=round(Sxy,2)
RoSxy
```

    ## [1] 128.88

By itself, the sample covariance \(128.88\) is not very meaningful. We
are not sure if this represents a small, moderate, or large amount of
relationship between \(y\) and \(x\). A method of standarizing the
covariance is given in the next section.

``` r
#plot
par(mfrow=c(2,2))
plot(x)
plot(x,type="l")
plot(y)
plot(y,type="l")
```

![](chapter3_examples_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

### Example 3-2-2

To obtain the correlation for the height and weight data of Table 3.1,
we first calculate the sample variance of \(x\) and \(y\):

**Variances**

``` r
S2x=var(x)
S2x
```

    ## [1] 14.57632

``` r
RoS2x=round(S2x,3)
RoS2x
```

    ## [1] 14.576

``` r
S2y=var(y)
S2y
```

    ## [1] 1441.274

``` r
RoS2y=round(S2y,3)
RoS2y
```

    ## [1] 1441.274

**Standard Deviation**

Then \(s_{x}\) and \(s_{y}\) equal:

``` r
Sx=sqrt(S2x)
Sx
```

    ## [1] 3.817894

``` r
RoSx=round(Sx,4)
RoSx
```

    ## [1] 3.8179

``` r
Sy=sqrt(S2y)
Sy
```

    ## [1] 37.96411

``` r
RoSy=round(Sy,3)
RoSy
```

    ## [1] 37.964

**Correlation between \(x\) and \(y\)**

And finally we get \(r_{xy}=\frac{s_{xy}}{s_{x}s_{y}}\), which is equal
to:

``` r
r=cor(x,y)
r
```

    ## [1] 0.8891701

``` r
Ror=round(r,3)
Ror
```

    ## [1] 0.889

### Example 3-6

Table 3.4 gives partial data from Kramer and Jensen (1969a). Three
variables were measured (in milliequivalents per 100 g) at 10 different
locations in the South. The variables are:

  - \(y_{1}\)= available soil calcium

  - \(y_{2}\)= exchangeanble soil calcium

  - \(y_{3}\)= turnip green calcium

<!-- end list -->

``` r
#defining "y" matrix (10 x 3)
y=matrix(c(35,35,40,10,6,20,35,35,35,30,3.5,4.9,30,2.8,2.7,2.8,4.6,10.9,
           8,1.6,2.8,2.7,4.38,3.21,2.73,2.81,2.88,2.9,3.28,3.2),10)
y
```

    ##       [,1] [,2] [,3]
    ##  [1,]   35  3.5 2.80
    ##  [2,]   35  4.9 2.70
    ##  [3,]   40 30.0 4.38
    ##  [4,]   10  2.8 3.21
    ##  [5,]    6  2.7 2.73
    ##  [6,]   20  2.8 2.81
    ##  [7,]   35  4.6 2.88
    ##  [8,]   35 10.9 2.90
    ##  [9,]   35  8.0 3.28
    ## [10,]   30  1.6 3.20

To obtain the mean vector \(\bar{y}\), we simply calculate the average
of each column and obtain:

``` r
#calcula el promedio por columna y luego toma los argumentos del vector renglón, transformandolo en un vector columna (con "cbind")
ybar=cbind(apply(y,2,FUN=mean))
#apply(X, MARGIN, FUN, ...)
#MARGIN: a vector giving the subscripts which the function will be applied over. E.g., for a matrix 1 indicates rows, 2 indicates columns, c(1, 2) indicates rows and columns. Where X has named dimnames, it can be a character vector selecting dimension names.
ybar
```

    ##        [,1]
    ## [1,] 28.100
    ## [2,]  7.180
    ## [3,]  3.089

``` r
#se le aplica la traspuesta ("t") a ybar
Tybar=t(ybar)
Tybar
```

    ##      [,1] [,2]  [,3]
    ## [1,] 28.1 7.18 3.089

### Example 3-7

To calculate the sample covariance matrix for the calcium data of Table
3.4 using the computational forms (3.24) and (3.26), we need the sum of
squares of each column and the sum of products of each pair of columns.
We illustrate the computation of \(s_{13}\)

\(\sum_{i=1}^{10}y_{i1}y_{i3}=(35)(2.80)+(35)(2.70)+...=885.48\)

From Example 3.6, we have \(\bar{y_{1}}=28.1\) and
\(\bar{y_{3}}=3.089\). By (3.26), we obtain
\(s{13}\)=\(\frac{1}{10-1}[885.48-10(28.1)(3.089)]=1.91412\)$

Continuing in this fashion, we obtain \(\textbf{S}\):

``` r
#estimating the covariance of "y"
S=cov(y)
S
```

    ##            [,1]      [,2]      [,3]
    ## [1,] 140.544444 49.680000 1.9412222
    ## [2,]  49.680000 72.248444 3.6760889
    ## [3,]   1.941222  3.676089 0.2501211

``` r
RoS=round(S,2)
RoS
```

    ##        [,1]  [,2] [,3]
    ## [1,] 140.54 49.68 1.94
    ## [2,]  49.68 72.25 3.68
    ## [3,]   1.94  3.68 0.25

### Example 3-8

In Example 3.7, we obtained the sample covariance matrix \(\textbf{S}\)
for the calcium data in Table 3.4. To obtain the sample correlation
matrix for the same data, we can calculate the individual elements using
(3.34) or use the direct matrix operation in (3.37). The diagonal matrix
\(\textbf{D}_{s}\) s can be found by taking the square roots of the
diagonal elements of \(\textbf{S}\),

``` r
#estimating the correlation of y
R=cor(y)
R
```

    ##           [,1]      [,2]     [,3]
    ## [1,] 1.0000000 0.4930154 0.327411
    ## [2,] 0.4930154 1.0000000 0.864762
    ## [3,] 0.3274110 0.8647620 1.000000

``` r
RoR=round(R,3)
RoR
```

    ##       [,1]  [,2]  [,3]
    ## [1,] 1.000 0.493 0.327
    ## [2,] 0.493 1.000 0.865
    ## [3,] 0.327 0.865 1.000

``` r
#the diagnonal of the covariance matrix of "y"
d=diag(diag(S))
d
```

    ##          [,1]     [,2]      [,3]
    ## [1,] 140.5444  0.00000 0.0000000
    ## [2,]   0.0000 72.24844 0.0000000
    ## [3,]   0.0000  0.00000 0.2501211

``` r
#root square of matrix d
D=sqrt(d)
D
```

    ##          [,1]     [,2]      [,3]
    ## [1,] 11.85514 0.000000 0.0000000
    ## [2,]  0.00000 8.499908 0.0000000
    ## [3,]  0.00000 0.000000 0.5001211

(note that we have used the unrounded version of \(\textbf{S}\) for
computation). Then by (3.37),

\[\textbf{R}=\textbf{D}_{s}^{-1}\textbf{S}\textbf{D}_{s}^{-1}\]

``` r
DI=solve(D)
DI
```

    ##            [,1]      [,2]     [,3]
    ## [1,] 0.08435157 0.0000000 0.000000
    ## [2,] 0.00000000 0.1176483 0.000000
    ## [3,] 0.00000000 0.0000000 1.999516

``` r
R=DI%*%S%*%DI
R
```

    ##           [,1]      [,2]     [,3]
    ## [1,] 1.0000000 0.4930154 0.327411
    ## [2,] 0.4930154 1.0000000 0.864762
    ## [3,] 0.3274110 0.8647620 1.000000

``` r
RoR=round(R,3)
RoR
```

    ##       [,1]  [,2]  [,3]
    ## [1,] 1.000 0.493 0.327
    ## [2,] 0.493 1.000 0.865
    ## [3,] 0.327 0.865 1.000

Note that \(.865 > .493 > .327\), which is a different order than that
of the covariances in \(\textbf{S}\) in Example 3.7. Thus we cannot
compare covariances, even within the same matrix \(\textbf{S}\).

``` r
S=D%*%R%*%D
S
```

    ##            [,1]      [,2]      [,3]
    ## [1,] 140.544444 49.680000 1.9412222
    ## [2,]  49.680000 72.248444 3.6760889
    ## [3,]   1.941222  3.676089 0.2501211

``` r
RoS=round(S,2)
RoS
```

    ##        [,1]  [,2] [,3]
    ## [1,] 140.54 49.68 1.94
    ## [2,]  49.68 72.25 3.68
    ## [3,]   1.94  3.68 0.25

### Example 3-9-1

Reaven and Miller (1979; see also Andrews and Herzberg 1985,
pp. 215-219) measured five variables in a comparison of normal patients
and diabetics. In Table 3.5 we give partial data for normal patients
only. The three variables of major interest were:

  - \(x_{1}\)= glucose intolerance
  - \(x_{2}\)= insuline response to oral glucose
  - \(x_{3}\)= insuline resistance

The two aditional variables of minor interest were:

  - \(y_{1}\)= relative weights
  - \(y_{2}\)= fasting plasma glucose

<!-- end list -->

``` r
x=matrix(c(356,289,319,356,323,381,350,301,379,296,353,306,290,371,
           312,393,364,359,296,345,378,304,347,327,386,365,365,352,325,321,360,
           336,352,353,373,376,367,335,396,277,378,360,291,269,318,328,124,117,
           143,199,240,157,221,186,142,131,221,178,136,200,208,202,152,185,116,
           123,136,134,184,192,279,228,145,172,179,222,134,143,169,263,174,134,
           182,241,128,222,165,282,94,121,73,106,55,76,105,108,143,165,119,105,
           98,94,53,66,142,93,68,102,76,37,60,50,47,50,91,124,74,235,158,140,
           145,99,90,105,32,165,78,80,54,175,80,186,117,160,71,29,42,56),46)
x
```

    ##       [,1] [,2] [,3]
    ##  [1,]  356  124   55
    ##  [2,]  289  117   76
    ##  [3,]  319  143  105
    ##  [4,]  356  199  108
    ##  [5,]  323  240  143
    ##  [6,]  381  157  165
    ##  [7,]  350  221  119
    ##  [8,]  301  186  105
    ##  [9,]  379  142   98
    ## [10,]  296  131   94
    ## [11,]  353  221   53
    ## [12,]  306  178   66
    ## [13,]  290  136  142
    ## [14,]  371  200   93
    ## [15,]  312  208   68
    ## [16,]  393  202  102
    ## [17,]  364  152   76
    ## [18,]  359  185   37
    ## [19,]  296  116   60
    ## [20,]  345  123   50
    ## [21,]  378  136   47
    ## [22,]  304  134   50
    ## [23,]  347  184   91
    ## [24,]  327  192  124
    ## [25,]  386  279   74
    ## [26,]  365  228  235
    ## [27,]  365  145  158
    ## [28,]  352  172  140
    ## [29,]  325  179  145
    ## [30,]  321  222   99
    ## [31,]  360  134   90
    ## [32,]  336  143  105
    ## [33,]  352  169   32
    ## [34,]  353  263  165
    ## [35,]  373  174   78
    ## [36,]  376  134   80
    ## [37,]  367  182   54
    ## [38,]  335  241  175
    ## [39,]  396  128   80
    ## [40,]  277  222  186
    ## [41,]  378  165  117
    ## [42,]  360  282  160
    ## [43,]  291   94   71
    ## [44,]  269  121   29
    ## [45,]  318   73   42
    ## [46,]  328  106   56

``` r
y=matrix(c(0.81,0.95,0.94,1.04,1,0.76,0.91,1.1,0.99,0.78,0.90,
           0.73,0.96,0.84,0.74,0.98,1.1,0.85,0.83,0.93,0.95,
           0.74,0.95,0.97,0.72,1.11,1.2,1.13,1,0.78,1,1,0.71,0.76,0.89,0.88,1.17,
           0.85,0.97,1,1,0.89,0.98,0.78,0.74,0.91,80,97,105,90,90,86,100,85,
           97,97,91,87,78,90,86,80,90,99,85,90,90,88,95,90,92,74,98,100,86,98,
           70,99,75,90,85,99,100,78,106,98,102,90,94,80,93,86),46)
y
```

    ##       [,1] [,2]
    ##  [1,] 0.81   80
    ##  [2,] 0.95   97
    ##  [3,] 0.94  105
    ##  [4,] 1.04   90
    ##  [5,] 1.00   90
    ##  [6,] 0.76   86
    ##  [7,] 0.91  100
    ##  [8,] 1.10   85
    ##  [9,] 0.99   97
    ## [10,] 0.78   97
    ## [11,] 0.90   91
    ## [12,] 0.73   87
    ## [13,] 0.96   78
    ## [14,] 0.84   90
    ## [15,] 0.74   86
    ## [16,] 0.98   80
    ## [17,] 1.10   90
    ## [18,] 0.85   99
    ## [19,] 0.83   85
    ## [20,] 0.93   90
    ## [21,] 0.95   90
    ## [22,] 0.74   88
    ## [23,] 0.95   95
    ## [24,] 0.97   90
    ## [25,] 0.72   92
    ## [26,] 1.11   74
    ## [27,] 1.20   98
    ## [28,] 1.13  100
    ## [29,] 1.00   86
    ## [30,] 0.78   98
    ## [31,] 1.00   70
    ## [32,] 1.00   99
    ## [33,] 0.71   75
    ## [34,] 0.76   90
    ## [35,] 0.89   85
    ## [36,] 0.88   99
    ## [37,] 1.17  100
    ## [38,] 0.85   78
    ## [39,] 0.97  106
    ## [40,] 1.00   98
    ## [41,] 1.00  102
    ## [42,] 0.89   90
    ## [43,] 0.98   94
    ## [44,] 0.78   80
    ## [45,] 0.74   93
    ## [46,] 0.91   86

``` r
Y=cbind(y,x)
Y
```

    ##       [,1] [,2] [,3] [,4] [,5]
    ##  [1,] 0.81   80  356  124   55
    ##  [2,] 0.95   97  289  117   76
    ##  [3,] 0.94  105  319  143  105
    ##  [4,] 1.04   90  356  199  108
    ##  [5,] 1.00   90  323  240  143
    ##  [6,] 0.76   86  381  157  165
    ##  [7,] 0.91  100  350  221  119
    ##  [8,] 1.10   85  301  186  105
    ##  [9,] 0.99   97  379  142   98
    ## [10,] 0.78   97  296  131   94
    ## [11,] 0.90   91  353  221   53
    ## [12,] 0.73   87  306  178   66
    ## [13,] 0.96   78  290  136  142
    ## [14,] 0.84   90  371  200   93
    ## [15,] 0.74   86  312  208   68
    ## [16,] 0.98   80  393  202  102
    ## [17,] 1.10   90  364  152   76
    ## [18,] 0.85   99  359  185   37
    ## [19,] 0.83   85  296  116   60
    ## [20,] 0.93   90  345  123   50
    ## [21,] 0.95   90  378  136   47
    ## [22,] 0.74   88  304  134   50
    ## [23,] 0.95   95  347  184   91
    ## [24,] 0.97   90  327  192  124
    ## [25,] 0.72   92  386  279   74
    ## [26,] 1.11   74  365  228  235
    ## [27,] 1.20   98  365  145  158
    ## [28,] 1.13  100  352  172  140
    ## [29,] 1.00   86  325  179  145
    ## [30,] 0.78   98  321  222   99
    ## [31,] 1.00   70  360  134   90
    ## [32,] 1.00   99  336  143  105
    ## [33,] 0.71   75  352  169   32
    ## [34,] 0.76   90  353  263  165
    ## [35,] 0.89   85  373  174   78
    ## [36,] 0.88   99  376  134   80
    ## [37,] 1.17  100  367  182   54
    ## [38,] 0.85   78  335  241  175
    ## [39,] 0.97  106  396  128   80
    ## [40,] 1.00   98  277  222  186
    ## [41,] 1.00  102  378  165  117
    ## [42,] 0.89   90  360  282  160
    ## [43,] 0.98   94  291   94   71
    ## [44,] 0.78   80  269  121   29
    ## [45,] 0.74   93  318   73   42
    ## [46,] 0.91   86  328  106   56

The mean vector, partitioned as in (3.41), is:

\[ \begin{pmatrix}
\bar{y}\\
\bar{x}
\end{pmatrix} = \begin{pmatrix}
\frac{\bar{y}_{1}\\
\bar{y}_{2}\\}
{\bar{x}_{1}\\
\bar{x}_{2}\\
\bar{x}_{3}\\}
\end{pmatrix}\]

``` r
Ybar=cbind(apply(Y,2,FUN=mean))
Ybar
```

    ##             [,1]
    ## [1,]   0.9178261
    ## [2,]  90.4130435
    ## [3,] 340.8260870
    ## [4,] 171.3695652
    ## [5,]  97.7826087

``` r
RoYbar=round(Ybar,2)
RoYbar
```

    ##        [,1]
    ## [1,]   0.92
    ## [2,]  90.41
    ## [3,] 340.83
    ## [4,] 171.37
    ## [5,]  97.78

The covariance matrix, partitioned as in the illustration following
(3.44) is:

``` r
S=matrix(var(Y),5)
S
```

    ##             [,1]       [,2]         [,3]         [,4]        [,5]
    ## [1,]  0.01618184   0.216029    0.7871691   -0.2138454    2.189072
    ## [2,]  0.21602899  70.558937   26.2289855  -23.9560386  -20.841546
    ## [3,]  0.78716908  26.228986 1106.4135266  396.7323671  108.383575
    ## [4,] -0.21384541 -23.956039  396.7323671 2381.8826087 1142.637681
    ## [5,]  2.18907246 -20.841546  108.3835749 1142.6376812 2136.396135

``` r
RoS=round(S,4)
RoS
```

    ##         [,1]     [,2]      [,3]      [,4]      [,5]
    ## [1,]  0.0162   0.2160    0.7872   -0.2138    2.1891
    ## [2,]  0.2160  70.5589   26.2290  -23.9560  -20.8415
    ## [3,]  0.7872  26.2290 1106.4135  396.7324  108.3836
    ## [4,] -0.2138 -23.9560  396.7324 2381.8826 1142.6377
    ## [5,]  2.1891 -20.8415  108.3836 1142.6377 2136.3961

Note that \(S_{yy}\) and \(S_{xx}\) are symmetric and that \(S_{xy}\) is
the transpose of \(S_{yx}\)

``` r
W=matrix(c(0.81,0.95,0.94,1.04,1,0.76,0.91,1.1,0.99,0.78,0.90,
           0.73,0.96,0.84,0.74,0.98,1.1,0.85,0.83,0.93,0.95,
           0.74,0.95,0.97,0.72,1.11,1.2,1.13,1,0.78,1,1,0.71,0.76,0.89,0.88,1.17,
           0.85,0.97,1,1,0.89,0.98,0.78,0.74,0.91,80,97,105,90,90,86,100,85,
           97,97,91,87,78,90,86,80,90,99,85,90,90,88,95,90,92,74,98,100,86,98,
           70,99,75,90,85,99,100,78,106,98,102,90,94,80,93,86,
           356,289,319,356,323,381,350,301,379,296,353,306,290,371,
           312,393,364,359,296,345,378,304,347,327,386,365,365,352,325,321,360,
           336,352,353,373,376,367,335,396,277,378,360,291,269,318,328,124,117,
           143,199,240,157,221,186,142,131,221,178,136,200,208,202,152,185,116,
           123,136,134,184,192,279,228,145,172,179,222,134,143,169,263,174,134,
           182,241,128,222,165,282,94,121,73,106,55,76,105,108,143,165,119,105,
           98,94,53,66,142,93,68,102,76,37,60,50,47,50,91,124,74,235,158,140,
           145,99,90,105,32,165,78,80,54,175,80,186,117,160,71,29,42,56),46)
W
```

    ##       [,1] [,2] [,3] [,4] [,5]
    ##  [1,] 0.81   80  356  124   55
    ##  [2,] 0.95   97  289  117   76
    ##  [3,] 0.94  105  319  143  105
    ##  [4,] 1.04   90  356  199  108
    ##  [5,] 1.00   90  323  240  143
    ##  [6,] 0.76   86  381  157  165
    ##  [7,] 0.91  100  350  221  119
    ##  [8,] 1.10   85  301  186  105
    ##  [9,] 0.99   97  379  142   98
    ## [10,] 0.78   97  296  131   94
    ## [11,] 0.90   91  353  221   53
    ## [12,] 0.73   87  306  178   66
    ## [13,] 0.96   78  290  136  142
    ## [14,] 0.84   90  371  200   93
    ## [15,] 0.74   86  312  208   68
    ## [16,] 0.98   80  393  202  102
    ## [17,] 1.10   90  364  152   76
    ## [18,] 0.85   99  359  185   37
    ## [19,] 0.83   85  296  116   60
    ## [20,] 0.93   90  345  123   50
    ## [21,] 0.95   90  378  136   47
    ## [22,] 0.74   88  304  134   50
    ## [23,] 0.95   95  347  184   91
    ## [24,] 0.97   90  327  192  124
    ## [25,] 0.72   92  386  279   74
    ## [26,] 1.11   74  365  228  235
    ## [27,] 1.20   98  365  145  158
    ## [28,] 1.13  100  352  172  140
    ## [29,] 1.00   86  325  179  145
    ## [30,] 0.78   98  321  222   99
    ## [31,] 1.00   70  360  134   90
    ## [32,] 1.00   99  336  143  105
    ## [33,] 0.71   75  352  169   32
    ## [34,] 0.76   90  353  263  165
    ## [35,] 0.89   85  373  174   78
    ## [36,] 0.88   99  376  134   80
    ## [37,] 1.17  100  367  182   54
    ## [38,] 0.85   78  335  241  175
    ## [39,] 0.97  106  396  128   80
    ## [40,] 1.00   98  277  222  186
    ## [41,] 1.00  102  378  165  117
    ## [42,] 0.89   90  360  282  160
    ## [43,] 0.98   94  291   94   71
    ## [44,] 0.78   80  269  121   29
    ## [45,] 0.74   93  318   73   42
    ## [46,] 0.91   86  328  106   56

``` r
Wbar=cbind(apply(W,2,FUN=mean))
Wbar
```

    ##             [,1]
    ## [1,]   0.9178261
    ## [2,]  90.4130435
    ## [3,] 340.8260870
    ## [4,] 171.3695652
    ## [5,]  97.7826087

``` r
RoWbar=round(Wbar,2)
RoWbar
```

    ##        [,1]
    ## [1,]   0.92
    ## [2,]  90.41
    ## [3,] 340.83
    ## [4,] 171.37
    ## [5,]  97.78

``` r
SW=matrix(var(W),5)
SW
```

    ##             [,1]       [,2]         [,3]         [,4]        [,5]
    ## [1,]  0.01618184   0.216029    0.7871691   -0.2138454    2.189072
    ## [2,]  0.21602899  70.558937   26.2289855  -23.9560386  -20.841546
    ## [3,]  0.78716908  26.228986 1106.4135266  396.7323671  108.383575
    ## [4,] -0.21384541 -23.956039  396.7323671 2381.8826087 1142.637681
    ## [5,]  2.18907246 -20.841546  108.3835749 1142.6376812 2136.396135

``` r
RoSW=round(SW,4)
RoSW
```

    ##         [,1]     [,2]      [,3]      [,4]      [,5]
    ## [1,]  0.0162   0.2160    0.7872   -0.2138    2.1891
    ## [2,]  0.2160  70.5589   26.2290  -23.9560  -20.8415
    ## [3,]  0.7872  26.2290 1106.4135  396.7324  108.3836
    ## [4,] -0.2138 -23.9560  396.7324 2381.8826 1142.6377
    ## [5,]  2.1891 -20.8415  108.3836 1142.6377 2136.3961

### Example 3-10-1

Timm (1975, p. 233; 1980, p. 47) reported the results of an experiment
in which subjects responded to “probe words” at five positions in a
sentence. The variables are response times for the jth probe word,
\(y_{j},j = 1,2,..., 5\). The data are given by \(Y\).

``` r
y=matrix(c(51,27,37,42,27,43,41,38,36,26,29,36,20,22,36,18,32,22,21,
           23,31,20,50,26,41,32,33,43,36,31,27,31,25,35,17,37,34,14,35,25,20,25,32,26,42,27,30,27,29,40,38,16,28,36,25),11)
y
```

    ##       [,1] [,2] [,3] [,4] [,5]
    ##  [1,]   51   36   50   35   42
    ##  [2,]   27   20   26   17   27
    ##  [3,]   37   22   41   37   30
    ##  [4,]   42   36   32   34   27
    ##  [5,]   27   18   33   14   29
    ##  [6,]   43   32   43   35   40
    ##  [7,]   41   22   36   25   38
    ##  [8,]   38   21   31   20   16
    ##  [9,]   36   23   27   25   28
    ## [10,]   26   31   31   32   36
    ## [11,]   29   20   25   26   25

``` r
y=matrix(c(51,27,37,42,27,43,41,38,36,26,29,36,20,22,36,18,32,22,21,
           23,31,20,50,26,41,32,33,43,36,31,27,31,25,35,17,37,34,14,35,25,20,25,
           32,26,42,27,30,27,29,40,38,16,28,36,25),11)
y
```

    ##       [,1] [,2] [,3] [,4] [,5]
    ##  [1,]   51   36   50   35   42
    ##  [2,]   27   20   26   17   27
    ##  [3,]   37   22   41   37   30
    ##  [4,]   42   36   32   34   27
    ##  [5,]   27   18   33   14   29
    ##  [6,]   43   32   43   35   40
    ##  [7,]   41   22   36   25   38
    ##  [8,]   38   21   31   20   16
    ##  [9,]   36   23   27   25   28
    ## [10,]   26   31   31   32   36
    ## [11,]   29   20   25   26   25

These variables are commensurate (same measurement units and similar
means and variances), and the researcher may wish to examine some simple
linear combinations. Consider the following linear combination for
illustrative purposes:

\[z=3y_{1}-2y_{2}+4y_{3}-y{4}+y_{5}\]

\[=(3, -2, 4, -1, 1)\textbf{y}= \textbf{a'y}\]

If \(z\) is calculated for each of the 11 observations, we obtain
\(z_{1}=288, z_{2} = 155, ... ,z_{11} = 146\) with mean
\(\bar{z} = 197.0\) and variance \(s_{z}^2 = 2084.0\).

These same results can be obtained using (3.54) and (3.55). The sample
**mean vector** and **covariance matrix** for the data are:

\(\bar{\textbf{y}}\):

``` r
ybar=cbind(apply(y,2,FUN=mean))
ybar
```

    ##          [,1]
    ## [1,] 36.09091
    ## [2,] 25.54545
    ## [3,] 34.09091
    ## [4,] 27.27273
    ## [5,] 30.72727

``` r
Roybar=round(ybar,2)
Roybar
```

    ##       [,1]
    ## [1,] 36.09
    ## [2,] 25.55
    ## [3,] 34.09
    ## [4,] 27.27
    ## [5,] 30.73

\(\textbf{S}\):

``` r
S=var(y)
S
```

    ##          [,1]     [,2]     [,3]     [,4]     [,5]
    ## [1,] 65.09091 33.64545 47.59091 36.77273 25.42727
    ## [2,] 33.64545 46.07273 28.94545 40.33636 28.36364
    ## [3,] 47.59091 28.94545 60.69091 37.37273 41.12727
    ## [4,] 36.77273 40.33636 37.37273 62.81818 31.68182
    ## [5,] 25.42727 28.36364 41.12727 31.68182 58.21818

``` r
RoS=round(S,2)
RoS
```

    ##       [,1]  [,2]  [,3]  [,4]  [,5]
    ## [1,] 65.09 33.65 47.59 36.77 25.43
    ## [2,] 33.65 46.07 28.95 40.34 28.36
    ## [3,] 47.59 28.95 60.69 37.37 41.13
    ## [4,] 36.77 40.34 37.37 62.82 31.68
    ## [5,] 25.43 28.36 41.13 31.68 58.22

Then, by (3.54),

\[\bar{z}=\textbf{a'}\bar{y}\]

``` r
a=cbind(c(3,-2,4,-1,1))
a
```

    ##      [,1]
    ## [1,]    3
    ## [2,]   -2
    ## [3,]    4
    ## [4,]   -1
    ## [5,]    1

``` r
z=t(a)%*%t(y)
z
```

    ##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
    ## [1,]  288  155  224  175  192  242  236  192  173   144   146

``` r
zbar=t(a)%*%ybar
zbar
```

    ##      [,1]
    ## [1,]  197

and by (3.55),

``` r
s2z=t(a)%*%S%*%a
s2z
```

    ##      [,1]
    ## [1,] 2084

We now define a second linear combination:

\[w=y_{1}+3y_{2}-y_{3}+y_{4}-2y_{5}\]

\[=(1, 3, -1, 2, -2)\textbf{y}= \textbf{b'y}\] The sample mean and
variance of \(w\) are \(\bar{w}=\textbf{b'}\bar{y}=44.45\) and
\(s_{w}^2=\textbf{b'Sb}=605.67\). The sample covariance of \(z\) and
\(w\) is by (3.56), \(s_{zw}=\textbf{a'Sb}=40.2\).

``` r
b=cbind(c(1,3,-1,1,-2))
b
```

    ##      [,1]
    ## [1,]    1
    ## [2,]    3
    ## [3,]   -1
    ## [4,]    1
    ## [5,]   -2

``` r
w=t(b)%*%t(y)
w
```

    ##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
    ## [1,]   60   24   39   98    4   51   20   58   47    48    40

``` r
wbar=t(b)%*%ybar
wbar
```

    ##          [,1]
    ## [1,] 44.45455

``` r
Rowbarb=round(wbar,2)
Rowbarb
```

    ##       [,1]
    ## [1,] 44.45

``` r
s2w=t(b)%*%S%*%b
s2w
```

    ##          [,1]
    ## [1,] 605.6727

``` r
Ros2w=round(s2w,2)
Ros2w
```

    ##        [,1]
    ## [1,] 605.67

``` r
Czw=t(a)%*%S%*%b
Czw
```

    ##      [,1]
    ## [1,] 40.2

##### Another Form

``` r
  f=function(y,a,b){
    ybar=cbind(apply(y,2,FUN=mean))
    Roybar=round(ybar,2)
    S=var(y)
    RoS=round(S,2)
    z=t(a)%*%t(y)
    w=t(b)%*%t(y)
    zbar=t(a)%*%ybar
    Rozbar=round(zbar,2)
    wbar=t(b)%*%ybar
    Rowbar=round(wbar,2)
    s2z=t(a)%*%S%*%a
    Ros2z=round(s2z,2)
    s2w=t(b)%*%S%*%a
    Ros2w=round(s2w,2)
    print(z)
    print(w)
    print(Roybar)
    print(RoS)
    print(Rozbar)
    print(Rowbar)
    print(Ros2z)
    print(Ros2w)
  }

y=matrix(c(51,27,37,42,27,43,41,38,36,26,29,36,20,22,36,18,32,22,21,
           23,31,20,50,26,41,32,33,43,36,31,27,31,25,35,17,37,34,14,35,25,20,25,
           32,26,42,27,30,27,29,40,38,16,28,36,25),11)

a=cbind(c(3,-2,4,-1,1))
b=cbind(c(1,3,-1,1,-2))
f(y,a,b)
```

    ##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
    ## [1,]  288  155  224  175  192  242  236  192  173   144   146
    ##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
    ## [1,]   60   24   39   98    4   51   20   58   47    48    40
    ##       [,1]
    ## [1,] 36.09
    ## [2,] 25.55
    ## [3,] 34.09
    ## [4,] 27.27
    ## [5,] 30.73
    ##       [,1]  [,2]  [,3]  [,4]  [,5]
    ## [1,] 65.09 33.65 47.59 36.77 25.43
    ## [2,] 33.65 46.07 28.95 40.34 28.36
    ## [3,] 47.59 28.95 60.69 37.37 41.13
    ## [4,] 36.77 40.34 37.37 62.82 31.68
    ## [5,] 25.43 28.36 41.13 31.68 58.22
    ##      [,1]
    ## [1,]  197
    ##       [,1]
    ## [1,] 44.45
    ##      [,1]
    ## [1,] 2084
    ##      [,1]
    ## [1,] 40.2

We now define three linear functions:

\[z_{1}=y_{1}+y_{2}+y_{3}+y_{4}+y_{5}\]
\[z_{2}=2y_{1}-3y_{2}+y_{3}-2y_{4}-y_{5}\]

\[z_{3}=-y_{1}-2y_{2}+y_{3}-2y_{4}+3y_{5}\] which can be written as:

\[\textbf{z}=\textbf{Ay}\]

``` r
A=matrix(c(1,2,-1,1,-3,-2,1,1,1,1,-2,-2,1,-1,3),3)
A
```

    ##      [,1] [,2] [,3] [,4] [,5]
    ## [1,]    1    1    1    1    1
    ## [2,]    2   -3    1   -2   -1
    ## [3,]   -1   -2    1   -2    3

``` r
S=var(y)
S
```

    ##          [,1]     [,2]     [,3]     [,4]     [,5]
    ## [1,] 65.09091 33.64545 47.59091 36.77273 25.42727
    ## [2,] 33.64545 46.07273 28.94545 40.33636 28.36364
    ## [3,] 47.59091 28.94545 60.69091 37.37273 41.12727
    ## [4,] 36.77273 40.33636 37.37273 62.81818 31.68182
    ## [5,] 25.42727 28.36364 41.12727 31.68182 58.21818

``` r
Z=A%*%t(y)
Z
```

    ##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
    ## [1,]  214  117  167  171  121  193  162  126  139   156   125
    ## [2,]  -68  -41  -55  -87  -24  -77  -36  -12  -48  -110   -54
    ## [3,]  -17    6  -24  -69   29  -14   15  -41  -21   -13   -21

and the sample mean vectorfor \(\txtbf{z}\) is given by (3.62) as:

\[\bar{z}=\textbf{A}\bar{y}\]

``` r
Zbar=cbind(apply(Z,1,FUN=mean))
Zbar
```

    ##           [,1]
    ## [1,] 153.72727
    ## [2,] -55.63636
    ## [3,] -15.45455

``` r
RoZbar=round(Zbar,2)
RoZbar
```

    ##        [,1]
    ## [1,] 153.73
    ## [2,] -55.64
    ## [3,] -15.45

and the sample covariance matrix of \(\txtbf{z}\) is given by (3.64) as:

\[S_{z}= \textbf{ASA'}\]

``` r
Sz=A%*%S%*%t(A)
Sz
```

    ##           [,1]      [,2]      [,3]
    ## [1,]  995.4182 -502.0909 -211.0364
    ## [2,] -502.0909  811.4545  268.0818
    ## [3,] -211.0364  268.0818  702.8727

``` r
RoSz=round(Sz,2)
RoSz
```

    ##         [,1]    [,2]    [,3]
    ## [1,]  995.42 -502.09 -211.04
    ## [2,] -502.09  811.45  268.08
    ## [3,] -211.04  268.08  702.87

The covariance matrix \[S_{x}\], can be converted to a correlation
matrix by use of (3.37):
\[R_{z}= \textbf{D}_{z}^{-1}\textbf{S}_{z}\textbf{D}_{z}^{-1}\]

``` r
Sz=A%*%S%*%t(A)
Sz
```

    ##           [,1]      [,2]      [,3]
    ## [1,]  995.4182 -502.0909 -211.0364
    ## [2,] -502.0909  811.4545  268.0818
    ## [3,] -211.0364  268.0818  702.8727

``` r
RoSz=round(Sz,2)
RoSz
```

    ##         [,1]    [,2]    [,3]
    ## [1,]  995.42 -502.09 -211.04
    ## [2,] -502.09  811.45  268.08
    ## [3,] -211.04  268.08  702.87

``` r
Dz=diag(sqrt(diag(Sz)))
Dz
```

    ##          [,1]     [,2]     [,3]
    ## [1,] 31.55025  0.00000  0.00000
    ## [2,]  0.00000 28.48604  0.00000
    ## [3,]  0.00000  0.00000 26.51175

``` r
RoDz=round(Dz,2)
RoDz
```

    ##       [,1]  [,2]  [,3]
    ## [1,] 31.55  0.00  0.00
    ## [2,]  0.00 28.49  0.00
    ## [3,]  0.00  0.00 26.51

``` r
IDz=solve(Dz)
IDz
```

    ##            [,1]       [,2]       [,3]
    ## [1,] 0.03169547 0.00000000 0.00000000
    ## [2,] 0.00000000 0.03510491 0.00000000
    ## [3,] 0.00000000 0.00000000 0.03771913

``` r
Rz=IDz%*%Sz%*%IDz
Rz
```

    ##            [,1]       [,2]       [,3]
    ## [1,]  1.0000000 -0.5586599 -0.2522994
    ## [2,] -0.5586599  1.0000000  0.3549743
    ## [3,] -0.2522994  0.3549743  1.0000000

``` r
RoRz=round(Rz,2)
RoRz
```

    ##       [,1]  [,2]  [,3]
    ## [1,]  1.00 -0.56 -0.25
    ## [2,] -0.56  1.00  0.35
    ## [3,] -0.25  0.35  1.00

where \(D_{z}\) is obtained from the square roots of the diagonal
elements of \(S_{z}\).

### Example 3-12

We illustrate the iterated regression method of estimating missing
values. Consider the calcium data of Table 3.4 as reproduced here and
suppose the entries in parentheses are missing:

``` r
#defining "y" matrix
y=matrix(c(35,35,40,10,6,20,35,35,35,30,3.5,4.9,30,2.8,2.7,2.8,4.6,10.9,
           8,1.6,2.8,2.7,4.38,3.21,2.73,2.81,2.88,2.9,3.28,3.20),10)
y
```

    ##       [,1] [,2] [,3]
    ##  [1,]   35  3.5 2.80
    ##  [2,]   35  4.9 2.70
    ##  [3,]   40 30.0 4.38
    ##  [4,]   10  2.8 3.21
    ##  [5,]    6  2.7 2.73
    ##  [6,]   20  2.8 2.81
    ##  [7,]   35  4.6 2.88
    ##  [8,]   35 10.9 2.90
    ##  [9,]   35  8.0 3.28
    ## [10,]   30  1.6 3.20

``` r
#mean per column and returning the result as a column vector.
ybar=cbind(apply(y,2,FUN=mean))
ybar
```

    ##        [,1]
    ## [1,] 28.100
    ## [2,]  7.180
    ## [3,]  3.089

``` r
#roundig the results of ybar to three decimals
Roybar=round(ybar,3)
Roybar
```

    ##        [,1]
    ## [1,] 28.100
    ## [2,]  7.180
    ## [3,]  3.089

``` r
#keeping rows 3-10 from column 2
y[3:10,2]
```

    ## [1] 30.0  2.8  2.7  2.8  4.6 10.9  8.0  1.6

We first regress \(y_{2}\) on \(y_{1}\) and \(y_{3}\) for observations
\(3-10\) and obtain \(\hat{y_{2}} = b_{0} + b_{1}y_{1} + b_{3}y_{3}\).

``` r
#lm is used to fit linear models. It can be used to carry out regression, single stratum analysis of variance and analysis of covariance (although aov may provide a more convenient interface for these). Inside the lm parenthesis we have to insert a formula, like the one provided below.
L2=lm(y[3:10,2]~y[3:10,1]+y[3:10,3])
L2
```

    ## 
    ## Call:
    ## lm(formula = y[3:10, 2] ~ y[3:10, 1] + y[3:10, 3])
    ## 
    ## Coefficients:
    ## (Intercept)   y[3:10, 1]   y[3:10, 3]  
    ##    -39.9433       0.1542      13.8011

When this is evaluated for the two nonmissing entries in the first row
(\(y_{1}\)= 35 and \(y_{3}\) = 2.80), we obtain \(\hat{y_{2}} = 4.097\).

``` r
yhat2=-39.9433+0.1542*y[1,1]+13.8011*y[1,3]
yhat2
```

    ## [1] 4.09678

``` r
Royhat2=round(yhat2,3)
Royhat2
```

    ## [1] 4.097

Similarly, we regress \(y_{3}\)on \(y_{1}\) and \(y_{2}\) for
observations \(3-10\) to obtain
\(\hat{y_{3}} = c_{0} + c_{1}y_{1} + c_{2}y_{2}\).

``` r
L3=lm(y[3:10,3]~y[3:10,1]+y[3:10,2])
L3
```

    ## 
    ## Call:
    ## lm(formula = y[3:10, 3] ~ y[3:10, 1] + y[3:10, 2])
    ## 
    ## Coefficients:
    ## (Intercept)   y[3:10, 1]   y[3:10, 2]  
    ##    2.814291    -0.001377     0.049941

Evaluating this for the two nonmissing entries in the second row yields
\(\hat{y_{3}} = 3.011\).

``` r
yhat3=2.814291+-0.001377*y[2,1]+0.049941*y[2,2]
yhat3
```

    ## [1] 3.010807

``` r
Royhat3=round(yhat3,3)
Royhat3
```

    ## [1] 3.011

We now insert these estimates for the missing values and calculate the
regression equations based on all 10 observations. Using the revised
equation \(\hat{y_{2}} = b_{0} + b_{1}y_{1} + b_{3}y_{3}\), we obtain a
new predicted value, \(\hat{y_{2}}= 3.698\).

Similarly, we obtain a revised regression equation for \(y_{3}\) that
gives a new predicted value, \(\hat{y_{3}} = 2.981\).

With these values inserted, we calculate new equations and obtain new
predicted values,\(\hat{y_{2}} = 3.672\) and \(\hat{y_{3}} = 2.976\). At
the third iteration we obtain \(\hat{y_{2}} = 3.679\) and
\(\hat{y_{3}} = 2.975\). There is very little change in subsequent
iterations.

These values are closer to the actual values, \(y_{2} = 3.5\) and
\({y_{3}}= 2.70\), than the initial regression estimates,
\(\hat{y_{2}} = 4.097\) and \(\hat{y_{3}} = 3.011\).

They are also much better estimates than the means of the second and
third columns, \(\bar{y_{2}}\) = 7.589 and \(\overline{y_{3}}\) = 3.132.
